#run
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "libs8787"
      - dependency-name: "blogs8787api.js"
